moved tokenize.py file to fix installation issues (via pip from github) + fixed tests
Version available in pip (https://pypi.org/project/rouge-score/) is outdated.

Installation from master:
```
pip install -e "git+https://github.com/google-research/google-research.git#egg=rouge_score&subdirectory=rouge
```
failed with:
```
File "/home/jupyter-apacuk/.conda/envs/encoder_decoder/lib/python3.8/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: module 'tokenize' has no attribute 'open'
```
due to file `tokenize.py` that hide standard library module `tokenize`.